[project]
name = "raiz"
version = "0.0.1"
requires-python = ">=3.12,<3.13"
dependencies = [
    "beautifulsoup4==4.14.3",
    "pydantic==2.12.5",
]

[dependency-groups]
dev = [
    "ruff==0.15.1",
]

[build-system]
requires = ["setuptools==82.0.0"]
build-backend = "setuptools.build_meta"
