on:
  - pull_request
env:
  RUFF_OUTPUT_FORMAT: github
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: astral-sh/ruff-action@v3.6.1
        with:
          src: "./raiz"
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: astral-sh/setup-uv@v7.3.0
      - run: uv sync --locked --all-extras --dev
        working-directory: ./raiz
      - run: uv run -m unittest
        working-directory: ./raiz
